# Generated by Django 4.2.2 on 2024-11-27 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название продукта"),
                ),
                (
                    "model",
                    models.CharField(max_length=50, verbose_name="Модель продукта"),
                ),
                ("release_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="NetworkLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(verbose_name="Уровень в сети")),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(max_length=50, verbose_name="Страна")),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Улица"
                    ),
                ),
                (
                    "house_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Номер дома"
                    ),
                ),
                (
                    "arrears",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Долг перед поставщиком"
                    ),
                ),
                ("create_date", models.DateField(auto_now_add=True)),
                (
                    "product",
                    models.ManyToManyField(
                        to="sales_network.product", verbose_name="Продукт"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales_network.networklink",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
    ]
